---
- hosts: all
  vars:
      sourcesList: /etc/apt/sources.list.d/beegfs-deb8.list
  tasks:
  - name: Add BeeGFS key
    shell: "wget -q https://www.beegfs.io/release/latest-stable/gpg/DEB-GPG-KEY-beegfs -O- | apt-key add -"
    
  - name: Add BeeGFS Repo
    shell: echo "deb [arch=amd64] http://www.beegfs.io/release/beegfs_6 deb8 non-free" > "{{ sourcesList }}"
   
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
        update_cache: yes

  - name: Update all packages to the latest version
    apt:
        upgrade: dist

- hosts: "tulip"
  tasks:
  - name: Install master bee 
    apt:
        name: beegfs-mgmtd 
        state: present

  - name: Install meta
    apt:
        name:  beegfs-meta
        state: present

  - name: Install admon
    apt:
        name:  beegfs-admon
        state: present

- hosts: hive
  tasks:
  - name: Install bees
    apt:
        name: beegfs-storage
        state: present
     
  - name: Bees client 
    apt: 
        name: beegfs-client
        state: latest

  - name: Bees helperd 
    apt: 
        name:  beegfs-helperd
        state: latest

  - name: Bees utils
    apt: 
        name: beegfs-utils
        state: latest

  - name: Bees common
    apt: 
        name: beegfs-common
        state: latest

  - name: Bees opentk-lib 
    apt: 
        name: beegfs-opentk-lib
        state: latest

  - name: XFS tools 
    apt: 
        name: "{{ item }}"
        state: latest        
    with_items:
          - - xfsprogs
            - xfsdump 
            - xfslibs-dev
