---
- hosts: manager
  vars:
    masterHome: /home/beegfs_mgmtd
  tasks:  
  - name: Configure Management Daemon mgmtd
    command: /opt/beegfs/sbin/beegfs-setup-mgmtd -p "{{ masterHome }}" creates=/home/beegfs-mgmtd-configured
  

- hosts: meta
  vars:
      metaHome: /home/beegfs_meta
      metaID: 0
      masterName: masterbee

  tasks:  
  - name: Configure META
    command: /opt/beegfs/sbin/beegfs-setup-meta -p "{{ metaHome }}" -s "{{ metaID }}" -m "{{ masterName }}" creates=/home/beegfs-meta-configured

- hosts: manager
  tasks:  
  - name: Configure Management Admon, sysMgmtdHost
    lineinfile:
               dest=/etc/beegfs/beegfs-admon.conf
               regexp="^sysMgmtdHost ="
               line="sysMgmtdHost = masterbee"

- hosts: manager
  vars:
      masterName: masterbee
  tasks:  
  - name: Configure Client
    command: /opt/beegfs/sbin/beegfs-setup-client -m "{{ masterName }}" creates=/home/beegfs-client-configured

#
# This should be done on all storage nodes, here also Manager cause is store as well
#
# Two options here, either global vars or better generate this using .sh script and file with server details,
#
- hosts: drone
  vars:
      masterName: masterbee
      storageHome: /mnt/store
      nodeNums:
          - - "1"
            - "2"
            - "3"
            
  tasks:  
  - name: Configure Stores, Script 
    command: /opt/beegfs/sbin/beegfs-setup-storage -p "{{ storageHome }}" -s "{{ item }}" -m "{{ masterName }}" creates=/home/beegfs-store0-configured
    with_items: "{{ nodeNums }}"

  - name: Configure Stores, Manual Node IDs
    command: echo store"{{ item }}" > /mnt/store/nodeID
    with_items: "{{ nodeNums }}"

# Add hosts entries for all Internal IPs and nodeIDs
- hosts: hive
  vars:
      hosts:
          - - "10.0.255.1 store0 masterbee meta0"
            - "10.0.255.100 store1"
            - "10.0.255.105 store2"
  tasks:
  - name: Add Hosts for internal traffic
    lineinfile:
      dest: /etc/hosts
      regexp: "^{{ item }}"
      line: "{{ item }}"
      owner: root
      state: present      
      create: False
    with_items: "{{ hosts }}"
   

